config/routes.rb
Rails.application.routes.draw do
  get 'archive/index'
  resources :food_logs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to:"food_logs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food_log.rb
class FoodLog < ApplicationRecord

    validates :calories , :proteins, :carbohydrates, :fats, :meal_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
  end
end

app/controllers/food_logs_controller.rb
class FoodLogsController < ApplicationController
  before_action :set_food_log, only: %i[ show edit update destroy ]

  # GET /food_logs or /food_logs.json
  def index
    @food_logs = FoodLog.all
  end

  # GET /food_logs/1 or /food_logs/1.json
  def show
    
  end

  # GET /food_logs/new
  def new
    @food_log = FoodLog.new
  end

  # GET /food_logs/1/edit
  def edit
  end

  # POST /food_logs or /food_logs.json
  def create
    @food_log = FoodLog.new(food_log_params)

    respond_to do |format|
      if @food_log.save
        format.html { redirect_to food_log_url(@food_log), notice: "Food log was successfully created." }
        format.json { render :show, status: :created, location: @food_log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_logs/1 or /food_logs/1.json
  def update
    respond_to do |format|
      if @food_log.update(food_log_params)
        format.html { redirect_to food_log_url(@food_log), notice: "Food log was successfully updated." }
        format.json { render :show, status: :ok, location: @food_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_logs/1 or /food_logs/1.json
  def destroy
    @food_log = FoodLog.find(params[:id])
    @food_log.destroy

    respond_to do |format|
      format.html { redirect_to food_logs_url, notice: "Food log was successfully destroyed." }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_log
      @food_log = FoodLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_log_params
      params.require(:food_log).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/food_logs_helper.rb
module FoodLogsHelper
end

app/views/archive/index.html.erb
<h1>Archive#index</h1>
<p>Find me in app/views/archive/index.html.erb</p>

app/views/food_logs/_food_log.html.erb
<div id="<%= dom_id food_log %>">
  <p>
    <strong>Meal type:</strong>
    <%= food_log.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= food_log.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= food_log.proteins %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= food_log.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= food_log.fats %>
  </p>

</div>

app/views/food_logs/_form.html.erb
<%= form_with(model: food_log,local: true) do |form| %>
  <% if food_log.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
      <p><%= pluralize(food_log.errors.count, "error") %> prohibited this food_log from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% food_log.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type,class: "label"  %>
    <%= form.text_field :meal_type ,class: "input" %>
  </div>

  <div>
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories,class: "input" %>
  </div>

  <div>
    <%= form.label :proteins,class: "label"  %>
    <%= form.number_field :proteins,class: "input" %>
  </div>

  <div>
    <%= form.label :carbohydrates,class: "label"  %>
    <%= form.number_field :carbohydrates,class: "input" %>
  </div>

  <div>
    <%= form.label :fats, class: "label"  %>
    <%= form.number_field :fats,class: "input" %>
  </div>

  <div>
    <%= form.submit class: "button-is-success" %>
  </div>
<% end %>

app/views/food_logs/edit.html.erb
<div class="cloumns is-centered mt-6">
  <div class="cloumn is-one-third">
    <h1 class="is-size-4 has-text-weight-bold mb-5">Editing Food Log</h1>
    <%= render 'form',food_log: @food_log %>
  </div>
</div>

<div>
<%= link_to "Home", food_logs_path,class: "button is-gray" %>
</div>

app/views/food_logs/index.html.erb
<% content_for :title do%>
  FoodLog &ndash; <%= DateTime.now.to_s%>
<% end %>

<div class="mt-6 is-centered">
   <% @food_logs.each do |food_log| %>
    <div class="column is one-quarter">
      <div class="card">
        <header class="card-header">
          <p class ="card-header-title"><%= food_log.meal_type %></p>
        </header>
        <div class="card-content">
          <div class="content">
          <p><span class="has-text-weight-bold"><%= food_log.calories%></span> calories</p>
          <p><span class="has-text-weight-bold"><%= food_log.proteins%></span> grams of proteins</p>
          <p><span class="has-text-weight-bold"><%= food_log.carbohydrates%></span> grams of carbohydrates</p>
          <p><span class="has-text-weight-bold"><%= food_log.fats%></span> grams of fats</p>
          <p class="italic"> Logged <%= time_ago_in_words(food_log.created_at)%> ago </p>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to "Show",food_log,class: "card-footer-item"%>
        <%= link_to "Edit",edit_food_log_path(food_log),class: "card-footer-item"%>
        <%= link_to "Destroy",food_log,method: :delete,data: {confirm: 'Are you sure?'},class: "card-footer-item"%>

      </div>
    </div>
  </div>
<% end %>




 
   

app/views/food_logs/new.html.erb
<div class="cloumns is-centered mt-6">
  <div class="cloumn is-one-third">
    <h1 class="is-size-4 has-text-weight-bold mb-5"> New Food Log</h1>
    <%= render 'form',food_log: @food_log %>
  </div>
</div>

app/views/food_logs/show.html.erb
<% content_for :title do %>
  <%= @food_log.meal_type%>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
    <p class="panel-heading">
    <%= @food_log.meal_type %>
    </p>

    <div class="panel-block">
      Calories: <%= @food_log.calories%>
    </div>

    <div class="panel-block">
      Proteins: <%= @food_log.proteins%>
    </div>

    <div class="panel-block">
      Carbohydrates: <%= @food_log.carbohydrates%>
    </div>

    <div class="panel-block">
      Fats: <%= @food_log.fats%>
    </div>
    </nav>

    <div class="column is-inline">
      <div class="column">
        <%= link_to "Edit",edit_food_log_path(@food_log),class: "button is-gray"%>
      </div>
      <div class="column">
        <%= link_to "Home", food_logs_path,class: "button is-gray" %>
      </div>
      <div class="column">
        <%= button_to "Delete",@food_log, method: :delete ,data: {confirm: "Are you sure? "},:remote=> true,class: " button is-gray" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    
  </head>

  <body>

   
    <%= render "shared/header"%>
    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %>
      </div>
      <% end %>
      <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %>
      </div>
      <% end %> 
    <div class="container">       
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-narrow">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Create New Entry ",new_food_log_path,class: "button is-success"%>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <h1 style="font-size:80px">Food Log</h1>
      </p>
      <p class="subtitle">
      </p>
    </div>
  </div>

  <!-- Hero footer: will stick at the bottom -->
</section>